### ISSUE TITLE
Timings

### ISSUE THREAD

**Issue by michel2323** [exanauts/ExaAdmm.jl#45]
@youngdae I see a lot of `CUDA.@timed @cuda` calls, like here https://github.com/exanauts/ExaAdmm.jl/blob/e62f00911b73a0987c0636b6f23bd219a547856e/src/models/acopf/acopf_admm_update_x_gpu.jl#L26

This only times the kernel launch or? Should we replace those with `CUDA.@timed CUDA.@sync @cuda` or does that lead to a slowdown?

**Comment by youngdae** [comment]
No. As far as I know, CUDA.@timed also synchronizes the kernel call. So it already contains CUDA.@sync. I tried to find its explanation, but I couldn't find it now...

**Comment by michel2323** [comment]
Yes, looked up now with `?CUDA.@timed`.
