### ISSUE TITLE
Multiperiod ACOPF on GPU

### ISSUE THREAD

**Issue by kibaekkim** [exanauts/ExaAdmm.jl#8]
# On branch `youngdae/abstraction`

Multiperiod ACOPF (mpacopf) is not passing the test on gpu.

## `CUDA@v3.4`

mpacopf runs the test only with `CUDA@v3.4`. Even this fails some tests for the values of `L_BR`.

## `CUDA@v3.5` and later

The test returns the following error:

```
Testing [x,xbar,z,l,lz] updates and a solve for MPACOPF: Error During Test at /home/kimk/REPOS/ExaAdmm.jl/test/algorithms/mpacopf_update_gpu.jl:1
  Got exception outside of a @test
  GPU compilation of kernel auglag_generator_kernel(Int64, Int64, Int64, Int64, Int64, Float64, Float64, CuDeviceVector{Float64, 1}, CuDeviceVector{Float64, 1}, CuDeviceVector{Float64, 1}, CuDeviceVector{Float64, 1}, CuDeviceVector{Float64, 1}, CuDeviceVector{Float64, 1}, CuDeviceVector{Float64, 1}, CuDeviceVector{Float64, 1}, CuDeviceVector{Float64, 1}, CuDeviceVector{Float64, 1}, CuDeviceVector{Float64, 1}, CuDeviceMatrix{Float64, 1}, CuDeviceVector{Float64, 1}, CuDeviceVector{Float64, 1}, CuDeviceVector{Float64, 1}, CuDeviceVector{Float64, 1}, CuDeviceVector{Float64, 1}, CuDeviceVector{Float64, 1}, CuDeviceVector{Float64, 1}, CuDeviceVector{Float64, 1}, Float64) failed
  KernelError: kernel returns a value of type `Union{}`

  Make sure your kernel function ends in `return`, `return nothing` or `nothing`.
  If the returned value is of type `Union{}`, your Julia code probably throws an exception.
  Inspect the code with `@device_code_warntype` for more details.
```

**Comment by kibaekkim** [comment]
I don't know if this is the source of the compiler error above.

I found that the line below may not be inlined by the compiler with `CUDA@v3.5` or later.
https://github.com/exanauts/ExaAdmm.jl/blob/99be676ff1988a1e1590d1013fea14deabf1969a/src/models/mpacopf/mpacopf_tron_generator_kernel.jl#L63

If I replace the line with the content of the function below, the compiler error disappears.
https://github.com/exanauts/ExaAdmm.jl/blob/99be676ff1988a1e1590d1013fea14deabf1969a/src/models/mpacopf/mpacopf_eval_generator_kernel_gpu.jl#L1-L30

**Comment by kibaekkim** [comment]
@wzhangw Can you take a look into the test results with `CUDA@v3.4`? All passed, except that some branch solutions do not match.

**Comment by michel2323** [comment]
Resolved in https://github.com/exanauts/ExaAdmm.jl/pull/9 .
